openapi: 3.0.1
info:
  title: lookup-tables
  description: Service which serve secret list data like countries, classification, etc.
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /lookup-tables/lookupData/{lookupKey}:
    get:
      operationId: getLookupData
      tags:
        - getLookupData
      summary: get lookup data
      parameters: 
      - name: lookupKey
        required: true
        in: path
        schema:
          type: string
      - name: excludeFieldsQuery
        allowReserved: true
        required: false
        in: query
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lookupOptionList'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /lookup-tables/capabilities:
    get:
      operationId: getCapabilities
      tags:
        - getCapabilities
      summary: get capabilities
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/capabilities'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    lookupOptionList:
      type: array
      items:
        $ref: '#/components/schemas/lookupOption'
    lookupOption:
      type: object
      required:
        - translationCode
        - value
      properties:
        translationCode:
          type: string
        value:
          type: string
    capabilities:
      type: array
      items:
        type: string
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
