{{- $MAIN_OBJECT_BLOCK := "configValues" -}}
{{- $COMPONENT_NAME := "backend" -}}
{{- $DATA := include "lookupTablesData" . -}}

{{- define "lookupTablesData" -}}
{{- $CONFIG_MANAGER_OBJECT := include "common.tplvalues.getGlobalObject" (dict "objName" "configManagment" "context" .) | fromYaml }}
{{- if not $CONFIG_MANAGER_OBJECT.enabled -}}
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
{{- end }}
  CONFIG_MANAGEMENT_URL: {{ $CONFIG_MANAGER_OBJECT.url | quote }}
{{- end -}}

{{ include "mc-chart.configmap" (dict "MAIN_OBJECT_BLOCK" $MAIN_OBJECT_BLOCK "COMPONENT_NAME" $COMPONENT_NAME "DATA" $DATA "WITH_TELEMETRY_TRACING" false "WITH_TELEMETRY_METRICS" false "context" .)}}
