{{- if .Values.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $chartName := include "lookup-tables.name" . -}}
{{- $cloudProviderDockerRegistryUrl := include "lookup-tables.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "lookup-tables.cloudProviderImagePullSecretName" . -}}
{{- $imageTag := include "lookup-tables.tag" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "lookup-tables.environment" . }}
    release: {{ $releaseName }}
    {{- include "lookup-tables.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "lookup-tables.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "lookup-tables.selectorLabels" . | nindent 8 }}
      {{- if .Values.resetOnConfigChange }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
    spec:
    {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
    {{- end }}
      containers:
        - name: {{ $releaseName }}-deployment
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.targetPort | quote }}
            - name: GIT_SSL_NO_VERIFY
              value: 'true'
            - name: CLASSIFIED_REPO_URL
              value: {{ .Values.env.classifiedRepoUrl | quote }}
          envFrom:
            - configMapRef:
                name: {{ $releaseName }}-configmap
          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: {{ .Values.env.targetPort }}
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
{{- end -}}
