{{- $cloudProviderFlavor := include "lookup-tables.cloudProviderFlavor" . -}}
{{- if and (and (.Values.enabled) (eq $cloudProviderFlavor "openshift")) (.Values.route.enabled) -}}
{{- $releaseName := .Release.Name -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $releaseName }}-lt
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
    {{- if .Values.route.timeout.enabled }}
    haproxy.router.openshift.io/timeout: {{ .Values.route.timeout.duration }}
    {{- end }}
spec:
  path:  {{ .Values.route.path | default "/" }}
  to:
    kind: Service
    name: {{ $releaseName }}-{{ $chartName }}
  port:
    targetPort: http
  {{- if .Values.route.tls }}
  tls:
    termination: edge
  {{- end }}
{{- end -}}
