{{- $releaseName := .Release.Name -}}
{{- $chartName := include "lookup-tables.name" . -}}
{{- $cloudProviderFlavor := include "lookup-tables.cloudProviderFlavor" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "lookup-tables.environment" . }}
    release: {{ $releaseName }}
    {{- include "lookup-tables.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ $targetPort }}
      protocol: TCP
      name: external
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
    {{- if .Values.rasterCommon.authentication.opa.enabled }}
    - port: {{ .Values.env.internalPort }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: TCP
      name: internal
    {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "lookup-tables.selectorLabels" . | nindent 4 }}
{{- end }}
