{{- if .Values.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $chartName := .Chart.Name -}}
{{- $cloudProviderFlavor := include "lookup-tables.cloudProviderFlavor" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "lookup-tables.environment" . }}
    release: {{ $releaseName }}
    {{- include "lookup-tables.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: {{ .Values.env.protocol }}
      name: http
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "lookup-tables.selectorLabels" . | nindent 4 }}
{{- end }}
