apiVersion: v2
name: lookup-tables
description: A Helm chart for lookup tables
type: application
version: 1.4.4
appVersion: 1.4.4
dependencies:
  - name: helm-common
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm
