global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030 #for minikube deployment only
resetOnConfigChange: true

cloudProvider:
  dockerRegistryUrl: acrarolibotnonprod.azurecr.io
  imagePullSecretName: my-registry-secret
  imagePullPolicy: Always
  flavor: openshift

caSecretName: ''
caPath: /usr/local/share/ca-certificates
caKey: ca.crt

image:
  repository: lookup-tables
  tag: v1.1.9

env:
  port: 80
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/traces
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  CLASSIFIED_REPO_URL: https://github.com/MapColonies/lookup-tables-data

resources:
  enabled: true
  value:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 1Gi

route:
  enabled: true
  host:
  path: /
  tls: true
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)

ingress:
  enabled: false
  host:
  path: /
  cors:
    enabled: true
    origin: '*'
  tls:
    useExternal:
